#!/usr/bin/env bash
# -----------------------
# @file print-term-colors
# @author erkanvatan
# @date 2025-02-04
# @brief Print color palette of terminal
# -----------------------

set -uo pipefail

readonly RESET=$'\033[0m'

for i in {0..255}; do
    printf '\033[38;5;%dmcolour%d%s\n' "$i" "$i" "$RESET"
done
