#!/usr/bin/env bash

set -E

function handle_err() {
    echo "An error has occured at line $1, exiting the script..." >&2
    exit $2
}

trap 'handle_err $LINENO $?' ERR

opts=$(getopt -o hs:d: -l help,src-iface:,dest-iface: -n "setup-ip-forwarding" -- "$@")

function show_help() {
    cat <<EOF
Setup IP forwarding between network interfaces

Usage: setup-ip-forwarding [OPTIONS]

Options:
  -h, --help
        show this help message
  -s, --src-iface=IFACE
        set source interface (REQUIRED)
  -d, --dest-iface=IFACE
        set destination interface (REQUIRED)
EOF
}

function parse_options() {
    src_iface=""
    dest_iface=""

    if [ $? != 0 ]; then
        exit 1
    fi

    eval set -- "$opts"

    while true; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            -s|--src-iface)
                src_iface="$2"
                shift 2
                ;;
            -d|--dest-iface)
                dest_iface="$2"
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "Error: getopt failed." >&2
                exit 1
                ;;
        esac
    done

    if [ -z "$src_iface" ] || [ -z "$dest_iface" ]; then
        show_help
        exit 1
    fi
}

function main() {
    parse_options

    sudo sysctl -w net.ipv4.ip_forward=1
    sudo iptables -A FORWARD -i "$dest_iface" -o "$src_iface" -j ACCEPT
    sudo iptables -A FORWARD -i "$src_iface" -o "$dest_iface" -m state --state RELATED,ESTABLISHED -j ACCEPT
    sudo iptables -t nat -A POSTROUTING -o "$src_iface" -j MASQUERADE
}

main
